# Generated by Django 5.0.2 on 2024-02-25 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('estado_actividad', models.CharField(choices=[('conectado', 'Conectado'), ('ausente', 'Ausente'), ('desconectado', 'Desconectado')], default='conectado', max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Electrodomestico',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('pequeños', 'Pequeños'), ('medianos', 'Medianos'), ('grandes', 'Grandes')], default='pequeños', max_length=20)),
                ('imagen', models.ImageField(upload_to='electrodomesticos/')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('consumo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stock', models.IntegerField(default=1)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Aplicacion.persona')),
            ],
            bases=('Aplicacion.persona',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Aplicacion.persona')),
            ],
            bases=('Aplicacion.persona',),
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_medicion', models.CharField(max_length=255)),
                ('maximo_consumo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.usuario')),
            ],
        ),
    ]
